apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip
  template:
    metadata:
      labels:
        app: ip
    spec:
      containers:
      - name: ip
        image: swr.af-south-1.myhuaweicloud.com/ralf/ip:928a1e9bf7b73136fc8a0dd2c7855f32348ed132
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      imagePullSecrets:
      - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ip
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: ip

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx  
  # tls:
  # - hosts:
  #   - ip.tf.work.gd
  #   secretName: ip-tls
  rules:
  - host: ip.tf.work.gd
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ip
            port:
              number: 80

