name: CI/CD to Huawei SWR and CCE

env:
  IMAGE_REGISTRY: swr.af-south-1.myhuaweicloud.com
  IMAGE_REPOSITORY: ralf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['date', 'frontend', 'ip', 'latency', 'random', 'time', 'uuid']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}



      - name: Update deployment image tags for services
        run: |
          for service in date frontend ip latency random time uuid; do
            sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/${service}:[a-z0-9]*@${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/$service:${{ github.sha }}@g" manifest/$service.yaml
            echo "Updated manifest/$service.yaml:"
            cat manifest/$service.yaml
          done


      - name: Commit and push manifest updates
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # First commit any manifest changes
          git add manifest/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit in manifest/"
          else
            git commit -m "Update image tags to ${{ github.sha }}"
          fi
          
          # Then sync with remote
          git fetch origin
          git pull --rebase origin main
          
          # Finally push changes
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
