name: CI/CD to Huawei SWR and CCE

env:
  IMAGE_REGISTRY: swr.af-south-1.myhuaweicloud.com
  IMAGE_REPOSITORY: ralf

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['date', 'frontend', 'ip', 'latency', 'random', 'time', 'uuid']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker image for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure kubectl for kubernetes Cluster
        run: |
          mkdir -p $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $KUBECONFIG
          chmod 600 $KUBECONFIG

      - name: Update deployment image for services
        run: |
          for service in date frontend ip latency random time uuid; do
            sed -i "s@docker-server/docker-org/${service}-api:image-version@${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/$service:${{ github.sha }}@g" manifest/$service.yaml
            echo "Updated manifest/$service.yaml:"
            cat manifest/$service.yaml
          done

      - name: Verify cluster access
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

      - name: Commit and push manifest updates
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Update local repo
          git fetch origin
          git rebase origin/main
          
          # Commit changes
          git add manifest/
          git commit -m "Update image tags to ${{ github.sha }}" || echo "No changes to commit"
          
          # Push changes
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      # - name: Commit and push manifest updates
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add manifest/
      #     git commit -m "Update image tags to ${{ github.sha }}"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}
